#!/bin/bash
# ============================================
# QaliSuite — Cron Jobs Setup
# Run as the deploy user:  bash deploy/setup-cron.sh [app-dir]
# ============================================
#
# Installs the five scheduled jobs and the small runner they share.
#
# WHY A RUNNER RATHER THAN curl IN THE CRONTAB: every /api/cron/* route requires
# `Authorization: Bearer $CRON_SECRET` and returns 401 without it. Putting the
# token in the crontab leaks it into `crontab -l` and into the process list of
# anyone running `ps`. The runner reads it from the .env file at 600.
#
# It does NOT `source` that file — .env is not shell (FROM_EMAIL contains
# `<noreply@...>`, which the shell parses as a redirect and dies on).

set -euo pipefail

APP_DIR="${1:-/opt/qalisuite}"
ENV_FILE="$APP_DIR/.env"
RUNNER="$APP_DIR/run-cron.sh"
LOG="/var/log/qalisuite-cron.log"

[ -f "$ENV_FILE" ] || { echo "No $ENV_FILE — create it first (see deploy/env.example)"; exit 1; }

if ! grep -q '^CRON_SECRET=.\+' "$ENV_FILE"; then
  echo "CRON_SECRET is missing or empty in $ENV_FILE."
  echo "Generate one:  openssl rand -hex 32"
  exit 1
fi

echo "==> Writing runner: $RUNNER"
cat > "$RUNNER" <<EOF
#!/bin/bash
# Generated by deploy/setup-cron.sh — calls one authenticated cron route.
# Usage: run-cron.sh <route-name> [timeout-seconds]
set -euo pipefail
ROUTE="\$1"; TIMEOUT="\${2:-60}"

SECRET=\$(sed -n 's/^CRON_SECRET=//p' "$ENV_FILE" | head -1 | tr -d "\"' ")
[ -n "\$SECRET" ] || { echo "CRON_SECRET missing from $ENV_FILE" >&2; exit 1; }

BASE=\$(sed -n 's/^APP_URL=//p' "$ENV_FILE" | head -1 | tr -d "\"' ")
BASE=\${BASE:-http://localhost:3000}

curl -fsS -m "\$TIMEOUT" -H "Authorization: Bearer \$SECRET" "\$BASE/api/cron/\$ROUTE"
EOF

chmod 700 "$RUNNER"

echo "==> Installing crontab (replacing any previous QaliSuite entries)"
# Drop our own lines only, so anything else in the user's crontab survives.
( crontab -l 2>/dev/null | grep -v "run-cron.sh" | grep -v "/api/cron/" || true ) > /tmp/qs-cron.$$

cat >> /tmp/qs-cron.$$ <<EOF
# ── QaliSuite scheduled jobs ────────────────────────────────────────────────
# Webhook retry — drains failed outbound deliveries queued in sync_logs.
* * * * * $RUNNER webhook-retry 60 >> $LOG 2>&1
# Stale approval reaper — frees requests stuck in 'applying' after a crash.
*/10 * * * * $RUNNER reap-approvals 60 >> $LOG 2>&1
# Daily alert digests (overdue invoices, low stock) — 06:00 EAT / 03:00 UTC.
0 3 * * * $RUNNER notify-alerts 300 >> $LOG 2>&1
# Mark absent — weekdays 15:00 UTC.
0 15 * * 1-5 $RUNNER mark-absent 120 >> $LOG 2>&1
# Notification pruning — Sundays 02:00 UTC.
0 2 * * 0 $RUNNER prune-notifications 300 >> $LOG 2>&1
EOF

crontab /tmp/qs-cron.$$
rm -f /tmp/qs-cron.$$

echo "==> Ensuring log file exists (needs sudo)"
sudo touch "$LOG" && sudo chown "$(id -u):$(id -g)" "$LOG" || \
  echo "    Could not create $LOG — create it manually, or cron output is lost."

echo "==> Installing logrotate rule (needs sudo)"
sudo tee /etc/logrotate.d/qalisuite-cron >/dev/null <<EOF || true
$LOG {
    weekly
    rotate 8
    compress
    missingok
    notifempty
    copytruncate
}
EOF

echo ""
echo "==> Installed:"
crontab -l | grep -E "run-cron.sh" | sed 's/^/    /'

echo ""
echo "==> Smoke test (should print JSON, not a 401):"
"$RUNNER" webhook-retry 30 || echo "    FAILED — check CRON_SECRET and that the app is running."

echo ""
echo "============================================"
echo "  Cron jobs configured"
echo "  Log: $LOG"
echo "============================================"
