import {
  pgTable,
  uuid,
  text,
  integer,
  numeric,
  timestamp,
  date,
  index,
  uniqueIndex,
} from "drizzle-orm/pg-core";
import { companies } from "./companies";
import { parties } from "./parties";
import { products } from "./products";

const money = (name: string) =>
  numeric(name, { precision: 19, scale: 4, mode: "string" });
const percent = (name: string) =>
  numeric(name, { precision: 9, scale: 4, mode: "string" });

/**
 * Quotes (0041).
 *
 * The totals are here so queries can select them; they are NOT for writing.
 * recalc_quote() owns subtotal, discount_total, tax_total and total, the same
 * way the request trigger owns total_value (§9.9) — a quote whose stored total
 * disagrees with its own lines is the defect that pattern exists to prevent.
 */
export const quotes = pgTable(
  "quotes",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    companyId: uuid("company_id")
      .notNull()
      .references(() => companies.id, { onDelete: "cascade" }),
    quoteNumber: text("quote_number").notNull(),

    customerId: uuid("customer_id").notNull(),
    // What the customer was told, at the time. See §9.4 on snapshots.
    customerName: text("customer_name").notNull(),
    customerEmail: text("customer_email"),
    customerPhone: text("customer_phone"),
    customerAddress: text("customer_address"),

    quoteDate: date("quote_date").notNull(),
    validUntil: date("valid_until"),
    status: text("status").notNull().default("draft"),

    title: text("title"),
    notes: text("notes"),
    internalNotes: text("internal_notes"),
    terms: text("terms"),
    reference: text("reference"),
    currency: text("currency").notNull().default("KES"),

    /** Derived by trigger. Read these; never write them. */
    subtotal: money("subtotal").notNull().default("0"),
    discountTotal: money("discount_total").notNull().default("0"),
    taxTotal: money("tax_total").notNull().default("0"),
    total: money("total").notNull().default("0"),

    sentAt: timestamp("sent_at", { withTimezone: true }),
    acceptedAt: timestamp("accepted_at", { withTimezone: true }),
    acceptedByName: text("accepted_by_name"),
    rejectedAt: timestamp("rejected_at", { withTimezone: true }),
    rejectionReason: text("rejection_reason"),
    cancelledAt: timestamp("cancelled_at", { withTimezone: true }),
    cancellationReason: text("cancellation_reason"),
    convertedAt: timestamp("converted_at", { withTimezone: true }),

    createdById: text("created_by_id"),
    createdByName: text("created_by_name"),
    createdByRole: text("created_by_role"),
    lastModifiedById: text("last_modified_by_id"),
    lastModifiedByName: text("last_modified_by_name"),
    createdAt: timestamp("created_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
  },
  (t) => [
    uniqueIndex("quotes_company_number_uq").on(t.companyId, t.quoteNumber),
    index("quotes_company_status_idx").on(t.companyId, t.status),
    index("quotes_company_date_idx").on(t.companyId, t.quoteDate),
    index("quotes_customer_idx").on(t.customerId),
  ],
);

/**
 * Quote lines (0041).
 *
 * Every amount is GENERATED by the database: discount then tax, in that order,
 * because tax is charged on what is payable. The source did the same in
 * JavaScript with Math.round(x * 100) / 100 per step, which is §2.1.
 *
 * There is no `invoicedQuantity`. How much of a line has been invoiced is what
 * the invoice lines say, and the `quote_line_invoiced` view asks them.
 */
export const quoteLines = pgTable(
  "quote_lines",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    companyId: uuid("company_id")
      .notNull()
      .references(() => companies.id, { onDelete: "cascade" }),
    quoteId: uuid("quote_id")
      .notNull()
      .references(() => quotes.id, { onDelete: "cascade" }),
    lineNumber: integer("line_number").notNull(),

    itemType: text("item_type").notNull(),
    serviceCategory: text("service_category"),

    productId: uuid("product_id"),
    productName: text("product_name"),
    productSku: text("product_sku"),

    description: text("description"),
    unit: text("unit"),
    quantity: money("quantity").notNull(),
    unitPrice: money("unit_price").notNull(),
    discountPercentage: percent("discount_percentage").notNull().default("0"),
    taxRate: percent("tax_rate").notNull().default("0"),

    /** All five GENERATED ALWAYS — selectable, never insertable. */
    grossAmount: money("gross_amount"),
    discountAmount: money("discount_amount"),
    netAmount: money("net_amount"),
    taxAmount: money("tax_amount"),
    lineTotal: money("line_total"),

    createdAt: timestamp("created_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
  },
  (t) => [
    uniqueIndex("quote_lines_number_uq").on(t.quoteId, t.lineNumber),
    index("quote_lines_quote_idx").on(t.quoteId),
  ],
);
